{
  # Import all your configuration modules here
  imports = [
    ./pi-nvim.nix
    ./nixos-path.nix
    ./system.nix
    ./options.nix
    ./dependencies.nix
    ./editor.nix
    ./ui.nix
    ./bufferline.nix
    ./mini.nix
    ./snippets.nix
    ./substitute.nix
    ./treesj.nix
    ./lspsaga.nix
    ./lsp-enhancements.nix
    ./session.nix
    ./git-enhancements.nix
    ./qol.nix
    ./indent.nix
    ./keymaps.nix
    ./navigation.nix
    ./treesit.nix
    ./lsp.nix
    ./lint.nix
    ./dap.nix
    ./cmp.nix
    ./format.nix
    ./term.nix
    ./obsidian.nix
    ./snacks.nix
    ./codecompanion.nix
    ./copilot.nix
    ./todo.nix
    ./trouble.nix
    ./indent-blankline.nix
    ./spectre.nix
    ./yanky.nix
    ./grug-far.nix
    ./tmux-zellij.nix
    ./sops.nix
  ];
}
